apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-depl
  labels:
    app: rest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-cont
        image: akhilp1468/rest-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: rest-registry
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  selector:
    app: rest-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-ingress
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: rest-service
      port:
        number: 8081
  rules:
  - host: rest.service.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rest-service
              port:
                number: 8081