  apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-depl
  labels:
    app: rest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-cont
        image: 
